main:
  - name: About
    url: "about/"
    weight: 10

  - name: Education
    url: "about/#education"
    parent: About
    weight: 11

  - name: Career
    url: "about/#experience"
    parent: About
    weight: 12

  - name: Project
    url: projects/
    weight: 20

  - name: Experience
    url: experience/
    weight: 30

  - name: Awards
    url: awards/
    weight: 50

  - name: Contact
    url: contact/
    weight: 60
